// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("saveDirectory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["saveDirectory"] = "";
        }
        if (!("startDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startDate"] = "";
        }
        if (!("endDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endDate"] = "";
        }
        if (!("dailyStartTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dailyStartTime"] = "";
        }
        if (!("dailyEndTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dailyEndTime"] = "";
        }
        if (!("intervalMinutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["intervalMinutes"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * "fullscreen" or "region"
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * "png" or "jpg"
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("regionX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["regionX"] = 0;
        }
        if (!("regionY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["regionY"] = 0;
        }
        if (!("regionW" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["regionW"] = 0;
        }
        if (!("regionH" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["regionH"] = 0;
        }
        if (!("autoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoStart"] = false;
        }
        if (!("showUIOnAutoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showUIOnAutoStart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}
