// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./pkg/config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(3902498144).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSchedulerRunning() {
    return $Call.ByID(733498938);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function MinimizeWindow() {
    return $Call.ByID(853425670);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenRegionSelector() {
    return $Call.ByID(3594854379);
}

/**
 * @param {config$0.Config | null} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(2775748437, cfg);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(886658577);
}

/**
 * @param {string} title
 * @returns {$CancellablePromise<void>}
 */
export function SetWindowTitle(title) {
    return $Call.ByID(2722182160, title);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartScheduler() {
    return $Call.ByID(2825364159);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopScheduler() {
    return $Call.ByID(2723123967);
}

/**
 * @param {$models.Region} r
 * @returns {$CancellablePromise<void>}
 */
export function SubmitRegion(r) {
    return $Call.ByID(3165501838, r);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
