// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Region {
    /**
     * Creates a new Region instance.
     * @param {Partial<Region>} [$$source = {}] - The source object to create the Region.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("w" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["w"] = 0;
        }
        if (!("h" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["h"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Region instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Region}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Region(/** @type {Partial<Region>} */($$parsedSource));
    }
}
