name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v0.1.0

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: amd64
            cgo: 0
            artifact_name: QuietSnap-Windows-amd64.exe
            build_cmd: go build -tags desktop,production -ldflags="-H windowsgui -s -w" -o QuietSnap-Windows-amd64.exe
          - os: windows-latest
            arch: arm64
            cgo: 0
            artifact_name: QuietSnap-Windows-arm64.exe
            build_cmd: go build -tags desktop,production -ldflags="-H windowsgui -s -w" -o QuietSnap-Windows-arm64.exe
          - os: macos-13
            arch: amd64
            cgo: 1
            artifact_name: QuietSnap-macOS-intel
            build_cmd: go build -tags desktop,production -ldflags="-s -w" -o QuietSnap-macOS-intel
          - os: macos-14
            arch: arm64
            cgo: 1
            artifact_name: QuietSnap-macOS-arm64
            build_cmd: go build -tags desktop,production -ldflags="-s -w" -o QuietSnap-macOS-arm64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install
        
      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
        
      - name: Build Backend
        run: ${{ matrix.build_cmd }}
        env:
          CGO_ENABLED: ${{ matrix.cgo }}
          GOARCH: ${{ matrix.arch }}
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
